# Generated by Django 4.2.4 on 2023-09-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parks",
            name="hightemp",
        ),
        migrations.RemoveField(
            model_name="parks",
            name="lowtemp",
        ),
        migrations.AddField(
            model_name="parks",
            name="image",
            field=models.ImageField(default="newtonhills.jpg", upload_to="images/"),
        ),
    ]
