# Generated by Django 4.2.4 on 2023-09-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_parks_hightemp_remove_parks_lowtemp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parks",
            name="image",
            field=models.ImageField(default="NewtonHills.jpg", upload_to="images/"),
        ),
    ]
